micronaut:
  application:
    name: spyfall
datasources:
  default:
    url: jdbc:mysql://localhost:3306/spyfall
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'password'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
#jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true